### ISSUE TITLE
Casting problems

### ISSUE THREAD

**Issue by unkilbeeg** [slhck/ffmpeg-bitrate-stats#3]
I had some trouble getting this to run.  Two lines ran into casting problems:

  File "/home/steve/.local/lib/python3.6/site-packages/ffmpeg_bitrate_stats/__main__.py", line 166, in _calculate_duration
    self.duration = self.frames[-1]["dts"] - self.frames[0]["dts"]
TypeError: unsupported operand type(s) for -: 'float' and 'str'

Fixed with 

    self.duration = float(self.frames[-1]["dts"]) - float(self.frames[0]["dts"])

And 

  File "/home/steve/projects/ffmpeg-bitrate-stats/ffmpeg_bitrate_stats/__main__.py", line 234, in <genexpr>
    sum_delta_time = sum(curr - prev for curr, prev in zip(times[1:], times))
TypeError: unsupported operand type(s) for -: 'str' and 'str'

Fixed with

    sum_delta_time = sum(float(curr) - float(prev) for curr, prev in zip(times[1:], times))

It may have been something funky with my media files.

**Comment by slhck** [comment]
This never happened for me. I'll check what's up. Probably the casting can be done earlier when parsing the output. It doesn't hurt at least.

**Comment by unkilbeeg** [comment]
Just found another one -- it had successfully processed over 800 video files before it hit one that triggered this:

  File "/home/steve/.local/lib/python3.6/site-packages/ffmpeg_bitrate_stats/__main__.py", line 209, in _collect_chunks
    agg_time += frame["duration"]
TypeError: unsupported operand type(s) for +=: 'int' and 'str'

My fix:

                       agg_time += float(frame["duration"])

**Comment by slhck** [comment]
Thanks! Do you have a clip that I can use to reproduce this? I think it's because of *NaN* values appearing.

**Comment by slhck** [comment]
Fixed in 0.1.3. Thanks for your contributions!
