### ISSUE TITLE
No Duration Output

### ISSUE THREAD

**Issue by tkoch96** [slhck/ffmpeg-bitrate-stats#4]
Sometimes ffprobe doesn't return "duration_time" after calling it. In this case, the current code returns "NaNs" for everything of interest. 

Can you think of a reason to not infer packet duration from "pts_time"? Here is modified code that makes things run nicely for me (on main.py).

![image](https://user-images.githubusercontent.com/10697990/74035422-39a95500-4988-11ea-9d73-074206d6ce4f.png)

**Comment by slhck** [comment]
Looks reasonable. It did not happen to me with my test files but I can imagine there are some where this is never set.

Could you perhaps provide a Pull Request with the modified code so I can test it? Thanks!

**Comment by slhck** [comment]
Actually, I think there may be a way to optimize this, let me look into it.

**Comment by slhck** [comment]
I rewrote the entire duration calculation in version 0.2.0. Please check if that works better for you.
